# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://huangxuan.me/yanshuo.io/
title: 演说.io
email: huxpro@gmail.com
author: 黄玄
description: > # "创作真正跨平台的 HTML5 展示文稿，让你的分享到达世界的任何一个角落
copyright: 'Copyright &copy; 2016 Yanshuo.io. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url:
